### ISSUE TITLE
Scorer doesn't work and validation fails

### ISSUE THREAD

**Issue by pfllo** [hunterhector/EvmEval#13]
Hi, sorry to bother again.

I tried to use scorer to evaluate the generated "gold.tbf" against itself following "demo_scorer.sh", which should perfectly match.
However, this program stuck after printing the information of the first doc on the terminal.

Then I tried "validator.py" to examine "gold.tbf", and it gives following error (part of it):

```
[ERROR] 2015-08-11 10:48:43,257 : Cannot find token file for doc [3f71fead3fa119ccdcdf01769ffee5b1] at [/Users/luo123n/Projects/event_detection/data/conversion/tkn/3f71fead3fa119ccdcdf01769ffee5b1.txt.tab], did you use correct file paths?
```

It seems "validator.py" expects the token file ends with ".txt.tab", while the tokenizer gives ".tab".

I'm not sure if this is the cause of the disfunction of scorer.

**Comment by hunterhector** [comment]
Hi,

There's nothing to sorry about, it is our problem and we would like to thank you for discovering them.

Here are two problems:
1. Validator, as you said, we did not read the correct extension, we've updated the default token extension. Yet the validator actually have the ability to specify a file extension, type "validator.py -h" for details.
2. Scorer, this is a recent known problem. 

We first developed this tool following the MUC's strategy, that enumerate all possible mappings and then report the highest score as the result. 

However, due to the change of the annotation scheme, there are now a large number of mentions that share the same span ( a.k.a double annotation) , this increases the number of possible mappings by a lot. In fact, for the first annotated file, we found 56 double annotations, which means there are 2^56 possible mappings. This is the reason for the scorer to be not responding.

We have plans for this problem and I am currently working on it. I will solve this asap.

**Comment by hunterhector** [comment]
We've update the scorer. It used to search for the best possible mapping for both mention detection and coreference. Now, due to the large number of double annotations, we decided to use a greedy method. This may produce slightly different scores from before.

**Comment by pfllo** [comment]
Thanks, it works now.

One imperfection is that, when I evaluate gold.tbf against itselft, some docs didn't score 100.0.
I think this is acceptable under these circumstances.

**Comment by hunterhector** [comment]
Hi,

I would like to see which part didn't get score 100? 

So actually there are 2 different problems here:
1. The score discrepancy is on the mention detection part:
   
   This should not happen if we score gold vs. gold. If you see that would you kindly let me know? Or   probably try to get the newest version of the scorer and try it again.
2. The score discrepancy is on the coreference part:
   
   a. There are chances that our greedy method make imperfect decision, we can't avoid that. But this doesn't seem to happen for LDC2015E73 data
   b. For each individual document scores, there are discrepancies introduced by the MUC metric. If you see the score is 75.00 for a document, this is related to the following issue:
   
   https://github.com/conll/reference-coreference-scorers/issues/2
   
   This will not affect the final scoring, but I could also try to take Sameer's suggestion that detect such cases in advance, and exclude MUC from the average when necessary.

**Comment by pfllo** [comment]
Hi.

The score is correct now.

It seems I used an old version gold.tbf before.

Thanks a lot.

**Comment by hunterhector** [comment]
Cool, thanks for letting me know, I actually update the source a little to incorporate the MUC problem.

Will close this issue now.
